### ISSUE TITLE
Deleted dashboards are still displayed in Analyze page

### ISSUE THREAD

**Issue by dengmingtong** [aws-solutions/clickstream-analytics-on-aws#494]
## Summary

Deleted dashboards are still displayed in Analyze page.
1. Create some dashboards in "Dashboards" page
2. Delete some of them.
3. Check "Analyzes" page, these deleted dashboards are still displayed in the pages.
<img width="1982" alt="Screenshot 2023-11-16 at 16 18 37" src="https://github.com/awslabs/clickstream-analytics-on-aws/assets/8953013/8d335a72-a83b-41c7-b023-0b02a58b6b86">

<img width="1443" alt="Screenshot 2023-11-16 at 16 19 04" src="https://github.com/awslabs/clickstream-analytics-on-aws/assets/8953013/dcb15084-2bf5-4408-badd-617499234776">

## Possible fixes

---

This is :bug: Bug Report

**Comment by zxkane** [comment]
Please check if there's still an issue with the latest version.

**Comment by mikeols** [comment]
Closed as stale.
